features:
  name: 1
  slogan: 1
  node_user_picture: 0
  comment_user_picture: 0
  favicon: 1
logo:
  use_default: 0
  path: sites/default/files/pixture_reloaded_logo.png
favicon:
  use_default: 0
  path: sites/default/files/favicon.ico
