module:
  address: 0
  admin_toolbar: 0
  adminimal_admin_toolbar: 0
  aggregator: 0
  automated_cron: 0
  bg_image_formatter: 0
  big_pipe: 0
  block: 0
  block_class: 0
  block_content: 0
  breakpoint: 0
  chosen: 0
  chosen_field: 0
  chosen_lib: 0
  ckeditor: 0
  color: 0
  colorbox: 0
  comment: 0
  config: 0
  config_direct_save: 0
  contact: 0
  contextual: 0
  ctools: 0
  custom_formatters: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  environment_indicator: 0
  environment_indicator_ui: 0
  field: 0
  field_ui: 0
  file: 0
  filefield_paths: 0
  filter: 0
  flexslider: 0
  flexslider_fields: 0
  flexslider_views: 0
  geolocation: 0
  geolocation_google_places_api: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  image_url_formatter: 0
  imce: 0
  insert_view: 0
  libraries: 0
  link: 0
  media: 0
  media_library: 0
  menu_block: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  migrate_plus: 0
  migrate_tools: 0
  migrate_upgrade: 0
  module_filter: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  php: 0
  quickedit: 0
  rdf: 0
  responsive_bg_image_formatter: 0
  responsive_image: 0
  search: 0
  shortcut: 0
  simple_block: 0
  superfish: 0
  system: 0
  taxonomy: 0
  taxonomy_manager: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_ui: 0
  forum: 1
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
