features:
  name: 0
  slogan: 1
  node_user_picture: 0
  comment_user_picture: 0
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://logo-edn.png'
favicon:
  use_default: 0
  path: 'public://favicon_0.ico'
  mimetype: image/vnd.microsoft.icon
