favicon:
  mimetype: image/vnd.microsoft.icon
  path: sites/default/files/favicon.ico
  url: ''
  use_default: true
features:
  comment_user_picture: false
  comment_user_verification: true
  favicon: true
  node_user_picture: false
  logo: true
  name: true
  slogan: true
logo:
  path: sites/default/files/logo.png
  url: ''
  use_default: true
_core:
  default_config_hash: 9rAU4Pku7eMBQxauQqAgjzlcicFZ2As6zEa6zvTlCB8
